### ISSUE TITLE
 Call to undefined function ModbusTcpClient\Network\mb_strtolower()

### ISSUE THREAD

**Issue by Elmatbaisaad** [aldas/modbus-tcp-client#109]
* Describe the problem
here is my code for reading holding registers:
 use ModbusTcpClient\Composer\Read\ReadRegistersBuilder;
use ModbusTcpClient\Network\NonBlockingClient;

require __DIR__ . '/../vendor/autoload.php';

$ip = 'tcp://127.0.0.1:12345';
$unitID = 0;
$fc3 = ReadRegistersBuilder::newReadHoldingRegisters($ip,$unitID)
    ->int16(0,'Register:')
    ->build();
$reponseContainer = (new NonBlockingClient(['readTimeoutSec' => 0.2]))->sendRequests($fc3);
print_r($reponseContainer->getData());
print_r($reponseContainer->getErrors());

- I keep getting  Call to undefined function ModbusTcpClient\Network\mb_strtolower() error .
- can help me.

**Comment by aldas** [comment]
You need to have PHP `mbstring` extension installed
