### ISSUE TITLE
Vendor map

### ISSUE THREAD

**Issue by Dutchstyler** [aldas/modbus-tcp-client#11]
In the index,php file there is the line" Require Vendor/autoload.php
But where can i find that file? 

I try to make a modbus connection with a siemens S71200 PLC. So hopefully this is possible.

**Comment by aldas** [comment]
hi, this project uses Composer (https://getcomposer.org/) and 'vendor' folder is created by composer. so to get it working:

1. install composer
1. run 'composer install' in this project folder
1. ...
1. profit

watch this about Composer https://www.youtube.com/watch?v=ZocYVPP3nQY or https://www.youtube.com/watch?v=xobz4ELUHKA

I think this should work with S71200 but make sure that at first you try Modbus TCP. This library has 'experimental' support for Modbus RTU over tcp but it is not in master yet.
