### ISSUE TITLE
$doubleWord->getUInt32() crash on 32bits php 

### ISSUE THREAD

**Issue by AlbertVS** [aldas/modbus-tcp-client#16]
Hi

The $doubleWord->getUInt32() function crash without errors when tring to get negative int for 32 bits php.
the Types::parseUInt32() return float when is 32 bits php but the getUInt32  (that call that functions) force the int conversion crashing when that is not possible.

The workarround is to check if php is 32 bit and call Types::parseUInt32() directly instead $doubleWord->getUInt32().

**Comment by aldas** [comment]
Should work now. I've removed return type from that method.

**Comment by AlbertVS** [comment]
tested and works find now.

Thanks.
