### ISSUE TITLE
modbus-tcp-client-master\examples/../vendor/autoload.php): failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by Acrobyux** [aldas/modbus-tcp-client#2]
Just downloaded project, I can't find the vendor folder.

**Comment by Acrobyux** [comment]
![image](https://user-images.githubusercontent.com/33229973/32184805-091028a0-bd63-11e7-9dfc-33e5be252331.png)

**Comment by aldas** [comment]
hi, this project uses Composer (https://getcomposer.org/) and 'vendor' folder is created by composer. so to get it working:

1. install composer 
2. run 'composer install' in this project folder
3. ...
4. profit

**Comment by Acrobyux** [comment]
I must install composer inside of project folder?
modbus-tcp-client-master

**Comment by aldas** [comment]
just watch this https://www.youtube.com/watch?v=ZocYVPP3nQY

**Comment by aldas** [comment]
@Acrobyux did you get it working for you?
