### ISSUE TITLE
where is the example fc4 located?

### ISSUE THREAD

**Issue by aliffirdi** [aldas/modbus-tcp-client#25]
i can't find fc4 example. can you help me?

**Comment by aldas** [comment]
fc4 has same API as fc3. So if you would replace in https://github.com/aldas/modbus-tcp-client/blob/master/examples/fc3.php 

1. `ReadHoldingRegistersRequest` to `ReadInputRegistersRequest` 
2. `ReadHoldingRegistersResponse` to `ReadInputRegistersResponse`

you would have example for fc4

**Comment by aldas** [comment]
Now there is an example of this
https://github.com/aldas/modbus-tcp-client/blob/1111df27d2ff9a176c4def1fe3fd7ba80863013a/examples/fc4.php#L17

**Comment by aliffirdi** [comment]
Thankyou very much. this is helpful :D
