### ISSUE TITLE
SlaveId for ModbusTCP

### ISSUE THREAD

**Issue by Nemecsek** [aldas/modbus-tcp-client#32]
`unitId` in `ReadRegistersBuilder::newReadHoldingRegisters  is 0 by default.

I found nowhere info about it and got quite a hard time to understand why my Janitza UMG604 device didn't work.  

It would be nice to **add a note about how to set the Slave Id**: 
`$fc3 = ReadRegistersBuilder::newReadHoldingRegisters('tcp://127.0.0.1:502', 1)`

**Comment by aldas** [comment]
updated docs. please could you make a pull request if you think it need more documentation.

**Comment by Nemecsek** [comment]
Thanks
