### ISSUE TITLE
Unable to use Uint on F6 due validate() validates only int16.

### ISSUE THREAD

**Issue by rfsales** [aldas/modbus-tcp-client#39]
We are trying to set value '65534' on a Uint16 address but an exception occurred:

Uncaught ModbusTcpClient\Exception\InvalidArgumentException: value is not set or out of range (int16): 65534 in .../aldas/modbus-tcp-client/src/Packet/ModbusFunction/WriteSingleRegisterRequest.php:38

Function 6, file: src/Packet/ModbusFunction/WriteSingleRegisterRequest.php

public function validate()
    {
        parent::validate();
        if ((null !== $this->value) && (($this->value >= Types::MIN_VALUE_INT16) && ($this->value <= Types::MAX_VALUE_INT16))) {
            return;
        }
        throw new InvalidArgumentException("value is not set or out of range (int16): {$this->value}");
    }

**Comment by aldas** [comment]
fixed. created new bugfix version 1.1.2

**Comment by rfsales** [comment]
Aldas as always solving the world problems!!!
Thanks a lot!
