### ISSUE TITLE
autoload.php

### ISSUE THREAD

**Issue by piotrw-git** [aldas/modbus-tcp-client#41]
Hello,
What does the autoload.php file contain?

**Comment by aldas** [comment]
Do you mean file `vendor/autoload.php`? This is composer autoloading file see `https://getcomposer.org/doc/`

this library is meant to be used with `composer` https://getcomposer.org/

**Comment by piotrw-git** [comment]
Hello,

Sorry, I still don't understand what this file should contain?

Which files are required additionally?

I have always used require_once ()

 

--
Pozdrawiam

Piotr WŁOSZYŃSKI
GSM +48 661 771 803

**Comment by aldas** [comment]
I strongly suggest that you read what composer is. Please see

- https://www.youtube.com/watch?v=I6wm15OWyqg
- https://www.youtube.com/watch?v=d_zPOJ8cz_A
- https://www.codewall.co.uk/how-to-install-use-composer-tutorial-for-dummies-with-pdf/

this will help you in the future
