### ISSUE TITLE
Extend the maximum read time of a request in higher level

### ISSUE THREAD

**Issue by marioshtika** [aldas/modbus-tcp-client#44]
Hello @aldas ,

I am using your example on [parallel request with amp](https://github.com/aldas/modbus-tcp-client/blob/master/examples/example_parallel_requests_amp.php). 
I am trying to simultaneously connect and read multiple units.

Some of the request are giving me the below error
```
Connecting to tcp://192.168.0.223:502 failed: timeout exceeded (10000 ms)
```

In the low level I am using the `->setReadTimeoutSec(20)` command.
Is there a way to do the same in the higher level?

Thank you in advance.

**Comment by aldas** [comment]
You can set Context for connect() method

```
            $connectContext = (new ConnectContext)->withConnectTimeout(1000); // 1sec
            /** @var \Amp\Socket\ClientSocket $socket */
            $socket = yield connect($request->getUri(), $connectContext);
```

but connect timeout and read timeout are different things.

**Comment by aldas** [comment]
Closing this ticket atm. PhpAmp library related questions are better to be asked at their repo.
