### ISSUE TITLE
High level API should support custom endian for each address

### ISSUE THREAD

**Issue by aldas** [aldas/modbus-tcp-client#81]
See discussion https://github.com/aldas/modbus-tcp-client/discussions/80

> I'd prefer the high-level API for my system, but I need another endian (BIG_ENDIAN_LOW_WORD_FIRST)). Is ist possible to change endian directly for each address. Maybe something like this from your example
->int16(657, 'battery3_voltage_wo','BIG_ENDIAN_LOW_WORD_FIRST')
or is it a must to use the low-level solution for another endian?

**Comment by gutschein** [comment]
Would be nice, But as the change of the default endian was alreday very helpfull it may deserve a line in the hel in chapter "Endianness": 
"Changing the default endian: `Endian::$defaultEndian = Endian::<needed_endian>;`"
