### ISSUE TITLE
decode modBus binary stream

### ISSUE THREAD

**Issue by skydiablo** [aldas/modbus-tcp-client#88]
hi,
i'm not really handy with modBus but i have already received the binary stream data via LoRaWAN. how can i decode this stuff to a more readable value? is modBus already defined in all details so i do not have to define an data-template or what is to do?

thx,
volker.

**Comment by aldas** [comment]
could you please describe your setup more closely. modbus is request/response protocol and term `stream` confuses me a little. You can decode modbus response packets but you still would have raw register data and this needs to be unpacked to separate address values - but this information how to do it is not contained in response. You would receive for example 4 registers of data but wther you should read 4 int16 values or 2 int32 or float there is up to you decide.

**Comment by skydiablo** [comment]
this is my example payload:

    $payload = base64_decode('DAYnARUADBRjaVEACy0AAAALOwIA8ApaVAIKXlcCDHhUOVhnAv0XAAAA');

and this is the payload definition: https://www.elvaco.se/Image/GetDocument/en/286/cmi4110-users-manual-english.pdf#page=15

so can i use this library to decode the payload?

**Comment by aldas** [comment]
This manual/document talks about M-Bus. M-Bus (Meter-Bus) and Modbus are different things. From that document it seems that you could set it to send even JSON. In that case it would be very easy to convert into php objects/arrays.

**Comment by skydiablo** [comment]
ahhhh !!!! M-Bus -vs- ModBus !!! okay, i see... yes, this module supports already JSON, but there is just a little peace of information to use the M-Bus style. so i have to decode the M-Bus style and i have it solved it just now by my own. so big thx for help and clear the missunderstood between "M-Bus" and "ModBus".
